# Use an official Python runtime as a parent image
FROM nginx:alpine

# Set the working directory to /mnt
WORKDIR /mnt

# Copy the current directory contents into the container at /mnt
# ADD . /mnt
ADD ./configs /etc/nginx/conf.d